### PR TITLE
Fix file backend

### LINKED ISSUE #640: confd fails to read non-string keys when using file backend
The yaml file backend only has cases for string, array and map in the switch that loads values. As a result anything not matching those types will fail to load. I think the expected behavior would be to coerce everything else to string.

Example:

```
#!/bin/bash

DIR=`mktemp -d`
pushd $DIR
mkdir conf.d
mkdir templates

cat << EOF > conf.d/test.toml
[template]
keys = [
    "/foo/stringVal",
    "/foo/intVal",
]
src = "test.txt.tmpl"
dest = "test.txt"
EOF

cat << EOF > templates/test.txt.tmpl
string: {{getv "/foo/stringVal"}}
int: {{getv "/foo/intVal"}}
EOF

cat << EOF > test.yml
foo:
  stringVal: string
  intVal: 1234
EOF

confd -onetime -log-level debug -confdir . -backend file -file test.yml

cat test.txt
popd
rm -rf $DIR
```

Output:

```
2017-12-11T15:50:32-07:00  confd[31669]: INFO Backend set to file
2017-12-11T15:50:32-07:00  confd[31669]: INFO Starting confd
2017-12-11T15:50:32-07:00  confd[31669]: INFO Backend source(s) set to test.yml
2017-12-11T15:50:32-07:00  confd[31669]: DEBUG Loading template resources from confdir .
2017-12-11T15:50:32-07:00  confd[31669]: DEBUG Found template: conf.d/test.toml
2017-12-11T15:50:32-07:00  confd[31669]: DEBUG Loading template resource from conf.d/test.toml
2017-12-11T15:50:32-07:00  confd[31669]: DEBUG Retrieving keys from store
2017-12-11T15:50:32-07:00  confd[31669]: DEBUG Key prefix set to /
2017-12-11T15:50:32-07:00  confd[31669]: DEBUG Key Map: map[string]string{"/foo/stringVal":"string"}
2017-12-11T15:50:32-07:00  confd[31669]: DEBUG Got the following map from store: map[/foo/stringVal:string]
2017-12-11T15:50:32-07:00  confd[31669]: DEBUG Using source template templates/test.txt.tmpl
2017-12-11T15:50:32-07:00  confd[31669]: DEBUG Compiling source template templates/test.txt.tmpl
2017-12-11T15:50:32-07:00  confd[31669]: ERROR template: test.txt.tmpl:2:7: executing "test.txt.tmpl" at <getv "/foo/intVal">: error calling getv: key does not exist: /foo/intVal
2017-12-11T15:50:32-07:00  confd[31669]: FATAL template: test.txt.tmpl:2:7: executing "test.txt.tmpl" at <getv "/foo/intVal">: error calling getv: key does not exist: /foo/intVal
```

### LINKED ISSUE #667: YML-file backend does not honor Keys list from toml file
using the file backend with an yaml file the keys section from the toml file is ignored and ALL keys defined within the yaml file are exposed to the template. This produces wrong results for the templated file...

Example yaml backend file (test.yml):
<pre>
test:
  a:
    key: "value-a"
  b:
    key: "value-b"
</pre>

Template file (/etc/confd/templates/test.tmpl):
<pre>
My value is: {{ index (gets "/*/key") 0 }}
</pre>

Two different TOML files to either render key from "a" or "b":
<pre>
# toml file "test-a.toml" - should produce "My value is  {/a/key value-a}"
[template]
prefix = "/test"
src = "test.tmpl"
dest = "/tmp/test-a.txt"
keys = [
  "/a/"
]
</pre>
<pre>
# toml file "test-b.toml" - should produce "My value is  {/b/key value-b}"
[template]
prefix = "/test"
src = "test.tmpl"
dest = "/tmp/test-b.txt"
keys = [
  "/b/"
]
</pre>

Now running confd with these files produces the following output - look at output lines 11 and 12 - there should only be displayed the respective key "/a/key" or "/b/key" but not booth. This result differs from other backends like consul.

<pre>
/etc/confd/conf.d # confd -onetime -log-level debug -backend file -file /tmp/test.yml 
2018-02-15T11:38:52Z 23574631c64c confd[21]: INFO Backend set to file
2018-02-15T11:38:52Z 23574631c64c confd[21]: INFO Starting confd
2018-02-15T11:38:52Z 23574631c64c confd[21]: INFO Backend source(s) set to /tmp/test.yml
2018-02-15T11:38:52Z 23574631c64c confd[21]: DEBUG Loading template resources from confdir /etc/confd
2018-02-15T11:38:52Z 23574631c64c confd[21]: DEBUG Found template: /etc/confd/conf.d/template-a.toml
2018-02-15T11:38:52Z 23574631c64c confd[21]: DEBUG Loading template resource from /etc/confd/conf.d/template-a.toml
2018-02-15T11:38:52Z 23574631c64c confd[21]: DEBUG Found template: /etc/confd/conf.d/template-b.toml
2018-02-15T11:38:52Z 23574631c64c confd[21]: DEBUG Loading template resource from /etc/confd/conf.d/template-b.toml
2018-02-15T11:38:52Z 23574631c64c confd[21]: DEBUG Retrieving keys from store
2018-02-15T11:38:52Z 23574631c64c confd[21]: DEBUG Key prefix set to /test
2018-02-15T11:38:52Z 23574631c64c confd[21]: DEBUG Key Map: map[string]string{"/test/a/key":"value-a", "/test/b/key":"value-b"}
2018-02-15T11:38:52Z 23574631c64c confd[21]: DEBUG Got the following map from store: map[/test/a/key:value-a /test/b/key:value-b]
2018-02-15T11:38:52Z 23574631c64c confd[21]: DEBUG Using source template /etc/confd/templates/template.tmpl
2018-02-15T11:38:52Z 23574631c64c confd[21]: DEBUG Compiling source template /etc/confd/templates/template.tmpl
2018-02-15T11:38:52Z 23574631c64c confd[21]: DEBUG Comparing candidate config to /tmp/test-a.txt
2018-02-15T11:38:52Z 23574631c64c confd[21]: INFO Target config /tmp/test-a.txt out of sync
2018-02-15T11:38:52Z 23574631c64c confd[21]: DEBUG Overwriting target config /tmp/test-a.txt
2018-02-15T11:38:52Z 23574631c64c confd[21]: INFO Target config /tmp/test-a.txt has been updated
2018-02-15T11:38:52Z 23574631c64c confd[21]: DEBUG Retrieving keys from store
2018-02-15T11:38:52Z 23574631c64c confd[21]: DEBUG Key prefix set to /test
2018-02-15T11:38:52Z 23574631c64c confd[21]: DEBUG Key Map: map[string]string{"/test/b/key":"value-b", "/test/a/key":"value-a"}
2018-02-15T11:38:52Z 23574631c64c confd[21]: DEBUG Got the following map from store: map[/test/b/key:value-b /test/a/key:value-a]
2018-02-15T11:38:52Z 23574631c64c confd[21]: DEBUG Using source template /etc/confd/templates/template.tmpl
2018-02-15T11:38:52Z 23574631c64c confd[21]: DEBUG Compiling source template /etc/confd/templates/template.tmpl
2018-02-15T11:38:52Z 23574631c64c confd[21]: DEBUG Comparing candidate config to /tmp/test-b.txt
2018-02-15T11:38:52Z 23574631c64c confd[21]: INFO Target config /tmp/test-b.txt out of sync
2018-02-15T11:38:52Z 23574631c64c confd[21]: DEBUG Overwriting target config /tmp/test-b.txt
2018-02-15T11:38:52Z 23574631c64c confd[21]: INFO Target config /tmp/test-b.txt has been updated
/
</pre>

As an result the content of booth files produced is identically and did not differ as exprected:
<pre>
/etc/confd/conf.d # cat /tmp/test-a.txt
My value is: {/a/key value-a}

/etc/confd/conf.d # cat /tmp/test-b.txt
My value is: {/a/key value-a}

</pre>

### PR DESCRIPTION
**Pull request by AndrewChubatiuk**
* Fixes #667. Fixes #640
* Added support for multiple yaml files and directories
* Added -filter flag for files/directories filtering
* Added recursive file watcher

### CODE REVIEW

File: util/filestat_windows.go [hunk 1]
```diff
@@ -8,8 +8,8 @@ import (
 	"os"
 )
 
-// fileStat return a fileInfo describing the named file.
-func fileStat(name string) (fi fileInfo, err error) {
+// filestat return a FileInfo describing the named file.
+func filestat(name string) (fi FileInfo, err error) {
 	if isFileExist(name) {
```
Comment (okushchenko) [inline util/filestat_windows.go]: This one should be uppercase.

File: config.go [hunk 2]
```diff
@@ -97,7 +99,8 @@ func init() {
 	flag.StringVar(&clientKey, "client-key", "", "the client key")
 	flag.StringVar(&confdir, "confdir", "/etc/confd", "confd conf directory")
 	flag.StringVar(&configFile, "config-file", "", "the confd config file")
-	flag.StringVar(&yamlFile, "file", "", "the YAML/JSON file to watch for changes")
+	flag.Var(&yamlFile, "file", "the YAML file to watch for changes")
```
Comment (okushchenko) [inline config.go]: Add a comment to indicate that this var is only used by file backend.

File: config_test.go [hunk 3]
```diff
@@ -23,6 +23,7 @@ func TestInitConfigDefaultConfig(t *testing.T) {
 		Scheme:        "http",
 		SecretKeyring: "",
 		Table:         "",
+		Filter:			"*",
```
Comment (okushchenko) [inline config_test.go]: formatting

File: backends/file/client.go [hunk 4]
```diff
@@ -3,67 +3,129 @@ package file
...
+	for _, path := range c.filepath {
+		p, _, err := util.Lookup(path, c.filter)
+		if err != nil {
+			return nil, err
+		}
+		filePaths = append(filePaths, p...)
+	}
+
+	for _, path := range filePaths {
+		readFile(path, vars)
```
Comment (okushchenko) [inline backends/file/client.go]: Check for errors

File: backends/file/client.go [hunk 5]
```diff
@@ -3,67 +3,129 @@ package file
...
+		vars[key] = strconv.FormatBool(node.(bool))
+	case float64:
+		vars[key] = strconv.FormatFloat(node.(float64), 'f', -1, 64)
 	}
 	return nil
 }
 
+func (c *Client) watchChanges(watcher *fsnotify.Watcher, stopChan chan bool) ResultError {
+	outputChannel := make(chan ResultError)
+	go func() error {
```
Comment (okushchenko) [inline backends/file/client.go]: This one will cause goroutine leak. `WatchPrefix` function is actually called in a loop in the main function. `WatchPrefix` should block until it receives an event and exit afterward.

File: util/util.go [hunk 6]
```diff
@@ -0,0 +1,116 @@
...
+	switch mode := f.Mode(); {
+	case mode.IsDir():
+		return true, nil
+	case mode.IsRegular():
+		return false, nil
+	}
+	return false, nil
+}
+
+func Lookup(root string, pattern string) ([]string, []string, error) {
```
Comment (okushchenko) [inline util/util.go]: `Lookup` is very ambiguous. Rename it to `recursiveFindFiles` or something more appropriate.

File: resource/template/resource.go [hunk 7]
```diff
@@ -345,7 +346,7 @@ func runCommand(cmd string) error {
 // from the store, then we stage a candidate configuration file, and finally sync
 // things up.
 // It returns an error if any.
-func (t *TemplateResource) process() error {
+func (t *TemplateResource) generateConfigs() error {
```
Comment (okushchenko) [inline resource/template/resource.go]: `process` is actually a better name for this method because it is a method of a `TemplateResource` and we `process` a template.

File: resource/template/processor.go [hunk 8]
```diff
@@ -86,12 +89,25 @@ func (p *watchProcessor) Process() {
 		p.wg.Add(1)
 		go p.monitorPrefix(t)
 	}
+}
+
+func (p *watchProcessor) Process() {
+	defer close(p.doneChan)
+	p.reloadConfigs()
+	c := make(chan os.Signal, 1)
+	signal.Notify(c, syscall.SIGHUP)
```
Comment (okushchenko) [inline resource/template/processor.go]: Let's move the sighup handling / config reloading into a separate PR.

File: backends/file/client.go [hunk 9]
```diff
@@ -3,67 +3,129 @@ package file
...
+		for {
+			select {
+			case event := <-watcher.Events:
+				log.Debug("event:", event)
+				if event.Op&fsnotify.Write == fsnotify.Write ||
+					event.Op&fsnotify.Remove == fsnotify.Remove ||
+					event.Op&fsnotify.Create == fsnotify.Create ||
+					event.Op&fsnotify.Rename == fsnotify.Rename ||
```
Comment (okushchenko) [inline backends/file/client.go]: What is the purpose of handling Rename and Chmod events?
